export const supabaseUrl = 'https://syaypwklvsfupwlcgxqz.supabase.co'
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5YXlwd2tsdnNmdXB3bGNneHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MzM1NDksImV4cCI6MjA3MTUwOTU0OX0.LppfiiCCMPzVUVpzMwvETdEWBwSIv9fpXQi6Le06N5w'
